### ISSUE TITLE
Таблиця динаміки для ради доброчестності

### ISSUE THREAD

**Issue by e-golubenko** [automaidan/judges#120]
[Яку таблицю заповнити](https://docs.google.com/spreadsheets/d/193E45ckQKbGIA25sH4APZFkrIG3u0r83O9ljOO4j8vI/edit?usp=sharing)
[Якими данними](https://drive.google.com/file/d/0B_h5Hz8fkVIBaDN3bld3dkFRUHNpWjlENEhfa21xSnJfYTc4/view?usp=sharing)

На основі #118 можно зробити генератор CSV файлів.

**Comment by popenkomaksim** [comment]
Неактуально.
