### ISSUE TITLE
SPA routing. Make all links be HTML5 links prosud.info/judges/garnik_lyudmila__leonidivna – links

### ISSUE THREAD

**Issue by popenkomaksim** [automaidan/judges#19]
@IlyaLytvynov, I am proposing to use:

```
/
/about
/contacts
/analytics
/search
/judges/:judgeKey
```

as URI strings.
What do you think?

**Comment by IlyaLytvynov** [comment]
Already on dev 655ada5 2016-07-14 | Added small changes to routes

**Comment by popenkomaksim** [comment]
Sorry for misunderstanding.
I proposed use links without /#/

Currently:
http://prosud.info/#/judges/garnik_lyudmila__leonidivna
Suggested:
http://prosud.info/judges/garnik_lyudmila__leonidivna

What do you think about it?

**Comment by IlyaLytvynov** [comment]
Looks not so difficult, but need time to find some work solution

**Comment by popenkomaksim** [comment]
We need html5mode=true in router configuration.

**Comment by popenkomaksim** [comment]
Merged with #39
