### ISSUE TITLE
Second bunch of additional front-end tasks

### ISSUE THREAD

**Issue by popenkomaksim** [automaidan/judges#35]
1. ~~Feature.Заменять картинку по умолчанию на фото судьи.Есть фото у  avramenko_mikola_grigorovich.json garnik_lyudmila__leonidivna.json sokurenko_dmitro_mihaylovich.json~~
2. ~~Feature. Як живе — ведет на сранице по ссылке из модели. Будет у avramenko_mikola_grigorovich.json garnik_lyudmila__leonidivna.json sokurenko_dmitro_mihaylovich.json~~
3. ~~Feature. кликабильность "маєш інфо"~~ 
4. ~~Feature. страница "контакты"~~
5. ~~Bug. Поиск судьи на телефоне~~ https://www.dropbox.com/s/i7ml6ywj5oa7hc2/Screenshot%202016-07-13%2013.13.27.png?dl=0
6. ~~Bug. Надписи в профайле на телефоне~~ https://www.dropbox.com/s/2egfjfh0iwf6zxi/Screenshot%202016-07-13%2013.13.48.png?dl=0

**Comment by IlyaLytvynov** [comment]
All issues pushed to fe-dev ready to deploy

**Comment by popenkomaksim** [comment]
Data rescaped.
Verified.
Done.
