### ISSUE TITLE
Analytics page

### ISSUE THREAD

**Issue by popenkomaksim** [automaidan/judges#70]
Фильтры:
1) По годам(2013, 2014, 2015)
2) По областям
3) По департаментам
4) По имуществу:
-самый большой доход
-самый большой доход членов семье
-самый большой земельный участок
-самый большой дом
-самая большая квартира
-наибольшее количество квартир
-найбольшее количство домов
-найбольшее количество земельных участков
-найбольшее количество автомобилей
-~~самый большие подарки(деньги)~~
-самые большие счета в банках
5) судьи Майдана
6) За 2015 год
-найменшее количество рассмотренных дел
-найбольшее количество жалоб

**Comment by IlyaLytvynov** [comment]
I think, it's already implemented in newAnalytics branch

**Comment by popenkomaksim** [comment]
http://prosud.info/#/analytics?query=year%3D2014%26region%3D%25D0%2597%25D0%25B0%25D0%25BF%25D0%25BE%25D1%2580%25D1%2596%25D0%25B7%25D1%258C%25D0%25BA%25D0%25B0%2520%25D0%25BE%25D0%25B1%25D0%25BB%25D0%25B0%25D1%2581%25D1%2582%25D1%258C%26department%3D%25D0%2590%25D0%25BF%25D0%25B5%25D0%25BB%25D1%258F%25D1%2586%25D1%2596%25D0%25B9%25D0%25BD%25D0%25B8%25D0%25B9%2520%25D1%2581%25D1%2583%25D0%25B4%2520%25D0%2597%25D0%25B0%25D0%25BF%25D0%25BE%25D1%2580%25D1%2596%25D0%25B7%25D1%258C%25D0%25BA%25D0%25BE%25D1%2597%2520%25D0%25BE%25D0%25B1%25D0%25BB%25D0%25B0%25D1%2581%25D1%2582%25D1%2596%26statistic%3Dh

**Comment by popenkomaksim** [comment]
1) ~~«всі департаменти» по області~~
2) (?) на мобільних — просто текстом
3) ~~прізвища вилазять зліва і справа~~
4) (?) Призвіще І.П.
5) ~~не показувати аналітику з "0"~~

100500) Видати список усіх судей з домівками 200м2 +.

**Comment by popenkomaksim** [comment]
Analytics page on mobile devices moved to another ticket #106.
